# Generated by Django 2.0 on 2018-01-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectteam',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
