FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# TrelloLike

TrelloLike API for mobile project management application.

## Boards Collection [/boards]

### List All Boards [GET]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "Trello like app development",
            },
            {
                "id": 1,
                "name": "Marketing",
            }
        ]
        
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }


### Create a New Board [POST]

+ Request (application/json)

        {
            "name": "New project idea",
        }
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 201 (application/json)

    + Headers

            Location: /boards/2

    + Body

            {
                "id": 2,
                "name": "New project idea",
                "ownerID": 0
                "lists": []
            }

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }


### Add / Remove team memeber [POST /board/{board_id}/team/{user_id}]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 200 (application/json)
 
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }


## Lists Collection [/boards/{board_id}/lists]

+ Parameters
    + board_id (number) - ID of the Board in the form of an integer
    
### List All lists for board [GET]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "TODO",
                "tasks": [
                     {
                        "id": 0,
                        "name": "Landingpage design",
                        "description": "",
                        "priority": 3,
                        "deadline": "2017-11-11T08:40:51.620Z",
                        "finished": false
                    },
                
                ]
            },
            {
                "id": 1,
                "name": "DOING",
                 "tasks": [
                     {
                        "id": 1,
                        "name": "Landingpage design",
                        "description": "",
                        "priority": 3,
                        "deadline": "2017-11-11T08:40:51.620Z",
                        "finished": false
                    },
                
                ]
            },
            {
                "id": 2,
                "name": "DONE",
                "tasks": [
                     {
                        "id": 3,
                        "name": "API design",
                        "description": "",
                        "priority": 3,
                        "deadline": "2017-11-11T08:40:51.620Z",
                        "finished": false
                    },
                
                ]
            }
        ]
        
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }
        
### Create New list [POST]

+ Request (application/json)

        {
            "name": "Backlog",
        }
    + Headers

            Authorization: JWT_TOKEN: 1324        

+ Response 201 (application/json)

    + Headers

            Location: /boards/2/lists/3

    + Body

            {
                "id": 3,
                "name": "Backlog"
            }
            
            
## List [/boards/{board_id}/lists/{list_id}]

+ Parameters
    + board_id (number) - ID of the Board in the form of an integer
    + list_id (number) - ID of the List in the form of an integer
    
### View List Details [GET]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 200 (application/json)

        {
            "id": 3,
            "name": "Backlog"
        }

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }
        
### Delete List [DELETE]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }


## Tasks Collection [/boards/{board_id}/lists/{list_id}/tasks]

+ Parameters
    + board_id (number) - ID of the Board in the form of an integer
    + list_id (number) - ID of the List in the form of an integer

### List All Tasks [GET]
List of all tasks for given list

+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "Landingpage design",
                "description": "",
                "priority": 3,
                "deadline": "2017-11-11T08:40:51.620Z",
                "finished": false
            },
            {
                "id": 1,
                "name": "Api documentation",
                "description": "",
                "priority": 3,
                "deadline": "2017-11-11T08:40:51.620Z",
                "finished": false
            },
        ]

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }

### Create New Task [POST]
+ Request (application/json)

        {
            "name": "New idea",
            "description": "Do shtm",
            "priority": 3,
            "deadline": "2017-11-11T08:40:51.620Z",
        }
    + Headers

            Authorization: JWT_TOKEN: 1324        

+ Response 201 (application/json)

    + Headers

            Location: /boards/2/lists/3/tasks/2

    + Body

            {
                "id": 2
                "name": "New idea",
                "description": "Do shtm",
                "priority": 3,
                "deadline": "2017-11-11T08:40:51.620Z",
                "finished": false
            }
            
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }
        

## Task [/boards/{board_id}/lists/{list_id}/tasks/{task_id}]

+ Parameters
    + board_id (number) - ID of the Board in the form of an integer
    + list_id (number) - ID of the List in the form of an integer
    + task_id (number) - ID of the List in the form of an integer

### Get Task [GET]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 200 (application/json)

        {
            "id": 2
            "name": "New idea",
            "description": "Do shtm",
            "priority": 3,
            "deadline": "2017-11-11T08:40:51.620Z",
            "finished": false
        }
        
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        } 
        
### Edit task [PATCH]

+ Request (application/json)

        {
            "name": "New Name",
            "description": "Do shtm",
            "priority": 3,
            "deadline": "2017-11-11T08:40:51.620Z",
        }
    + Headers

            Authorization: JWT_TOKEN: 1324

+ Response 200 (application/json)

        {
            "id": 2
            "name": "New Name",
            "description": "Do shtm",
            "priority": 3,
            "deadline": "2017-11-11T08:40:51.620Z",
            "finished": false
        }
        
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }        

### Delete Task [DELETE]
+ Request
    + Headers

            Authorization: JWT_TOKEN: 1324
            
+ Response 204 (application/json)

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }

### Mark as completed [GET /boards/{board_id}/lists/{list_id}/tasks/{task_id}/completed]
Marks task as completed or uncompleted.
+ Request
    + Headers 
    
            Authorization: JWT_TOKEN: 1324

+ Response 200 (application/json)

        {
            "id": 2
            "finished": True
        }
        
+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }       

### Change list [GET /boards/{board_id}/lists/{list_id}/tasks/{task_id}/move/{new_list_id}]
Move task to another list
+ Request
    + Headers 
    
            Authorization: JWT_TOKEN: 1324

+ Response 200 (application/json)

+ Response 401 (application/json)

        {
            "detail": "Authentication credentials were not provided."
        }

+ Response 404 (application/json)

        {
            "detail": "Not found."
        }

## User's Account's [/accounts/register]

### Register  [POST]

+ Request (application/json)

        {
            "username": "Michal",
            "email": "michal@gmail.com",
            "password": "MyPassword123"
        }

+ Response 201 (application/json)

    + Headers

            Location: /boards/2

    + Body

            {
                "username": "Michal",
                "jwt_token": "sdsa231243ffddfd"
            }



### Login  [POST /accounts/login]

+ Request (application/json)

        {
            "username": "Michal",
            "password": "MyPassword123"
        }

+ Response 201 (application/json)

    + Headers

            Location: /boards/2

    + Body

            {
                "jwt_token": "sdsa231243ffddfd"
            }