# Generated by Django 2.0 on 2017-12-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171231_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='project_id',
            new_name='board_id',
        ),
    ]
